server:
  port: 8082

spring:
  application:
    name: Consumer
  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      group-id: jt-group-1
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
      properties:
        schema.registry.url: http://localhost:8081
        specific.avro.reader: true

app:
  topic:
    fallout: Fallout
    migration: Migration
